### PR TITLE
Replace thumbnail images on news page first three articles

### PR DESCRIPTION
**Pull request by direnakkoc**
The issue applied: https://github.com/CURIOSSorg/curioss.org/issues/38

News page now :
Screenshot 2024-08-29 at 10 25 13

### CODE REVIEW

**Comment by RichardLitt** [comment]
I think it's better to do this on the website - note how the borders are trimmed due to the CSS rounding. We should either turn that off and use the image templates, or just institute a rule in CSS to do this. Let me know if you need help.

**Comment by direnakkoc** [comment]
Hi @RichardLitt ,

We only want to upload images without needing to customise the CSS. I’m not sure if handling this with CSS is necessary. Instead, I suggest we use a standard image template whenever we upload news. This way, we can maintain a consistent look for all images.

Even if we add a nice box around the images, it won’t matter if the images themselves have green lines or other inconsistencies—they just won’t look right. By using a template, we can ensure all images appear uniform and professional.

If I'm mistaken please let me know :-)

**Comment by RichardLitt** [comment]
Screenshot 2024-08-29 at 10 18 42

Notice the clipped corner? This is, I think, from a CSS rule that rounds out the corners. If we are uploading them all with a border, we have to change that - or, we could not use a green border in the image template (which is much more annoying to fix later), and make a CSS rule that is easier to change for the future. 

I think CSS is ultimately easier here than using an image template that is static, but I may be wrong.

**Comment by direnakkoc** [comment]
Hi @RichardLitt ,

Yes, for the rounded part I agree. I removed the rounded label it should be fine now. I thought the issue related to the other side of the images below screenshot:
Screenshot 2024-08-29 at 10 15 52

**Comment by claredillon** [comment]
If we do it on the website - will it/can it have a border on both the summary page and the individual article page? If so - we can just remove from the image template.

**Comment by direnakkoc** [comment]
Hi @claredillon ,
Yes, it will have a green corner border on both the summary page and the individual article page not rounded. Same as in the screenshot above the first description that I posted.

**Comment by RichardLitt** [comment]
Happy to take another look when the images without the green borders have been uploaded. :)

**Comment by CiaraFlanagan** [comment]
Hi there @direnakkoc 

As a temporary measure, I would be grateful if you could upload the slides with the green border that Clare originally shared. Let's just get this done for now.

I'll approve a PR for this and then I'll revert to @RichardLitt and @claredillon for a final discussion on the proposed CSS solution.

**Comment by direnakkoc** [comment]
Hi @CiaraFlanagan ,
Here is the News page below now:
Screenshot 2024-09-10 at 22 00 53

**Comment by RichardLitt** [comment]
Works for me. Thank you!

**Pull request merged**
